### ISSUE TITLE
ToDo Tasks

### ISSUE THREAD

**Issue by dilanSachi** [lxhelmer/DistSys-project#3]
Next tasks

Work on the central server
- [ ] Work on file uploading part of the central server
- [ ] Work on distributing the files across the nodes by the server
- [ ] Node discovery

Work on subnodes
- [ ] Work on video playing part
- [ ] Work on communicating pause, play feature to other nodes
- [ ] Work on downloading new video files from the server

General tasks
- [ ] Need to logging for all nodes
